site_name: remorques_ateliers
nav:
    - Readme: README.md
    - 1. Choix de la remorque: choix_remorque.md
    - 2. Transformation: transformation.md
    - 3. Equipements:
      - 3.1. Serveur local: serveur_local.md
      
        
theme:
    name: material
    palette:
      primary: blue

plugins:
  - search
  - i18n:
      default_language: fr
      languages:
        fr: Fran√ßais

markdown_extensions:
    - smarty
    - sane_lists
    - admonition
    - toc:
        permalink: true
